<b> List excercise </b>

In [1]:
#1
colors = ['blue', 'white', 'green', 'red', 'pink', 'yellow']

In [2]:
#2
print(len(colors))

6


In [3]:
#3
'blue' in colors

True

In [4]:
#3
'purple' in colors

False

In [5]:
#4
color = 'white'
try:
    print(colors.index(color))
except:
    print("The color is not present.")

1


In [6]:
#4
color = 'black'
try:
    print(colors.index(color))
except:
    print("The color is not present.")

The color is not present.


In [7]:
#5
colors.append('violet')
colors.append('grey')
print(colors)

['blue', 'white', 'green', 'red', 'pink', 'yellow', 'violet', 'grey']


In [8]:
#6
colors.append(['black', 'brown'])
print(colors)

['blue', 'white', 'green', 'red', 'pink', 'yellow', 'violet', 'grey', ['black', 'brown']]


In [14]:
#7
for x in range(2):
    colors.pop(x)
colors[0] = 'cyan'
print(colors)

['cyan', 'red', 'pink', 'yellow', 'violet', 'grey', ['black', 'brown']]


In [15]:
#8
colors[6].append('orange')
print(colors)

['cyan', 'red', 'pink', 'yellow', 'violet', 'grey', ['black', 'brown', 'orange']]


In [16]:
#9
del colors[2:]
print(colors)

['cyan', 'red']


In [18]:
#10
lst = []
for i in range(5):
    innerlst = []
    for j in range(5):
        innerlst.append(5*i + j)
    lst.append(innerlst)
print(lst)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]


In [19]:
#11
numbers = [[1,2],[3,4],[5,6],[7,8,9]]
print(len(numbers[-1]))

3


In [20]:
#12
lst12 = []
for x in range(1,10,2):
    lst12.append(x**2)
print(lst12)

[1, 9, 25, 49, 81]


In [25]:
#13
lst13 = []
for x in range(1,11):
    lst13.append([3, x, 3*x])
print(lst13)

[[3, 1, 3], [3, 2, 6], [3, 3, 9], [3, 4, 12], [3, 5, 15], [3, 6, 18], [3, 7, 21], [3, 8, 24], [3, 9, 27], [3, 10, 30]]


In [26]:
#14
lst14 = []
for i in range(4):
    l = []
    for j in range(3):
        l2 = []
        for x in range(2):
            l2.append('?')
        l.append(l2)
    lst14.append(l)
print(lst14)
            

[[['?', '?'], ['?', '?'], ['?', '?']], [['?', '?'], ['?', '?'], ['?', '?']], [['?', '?'], ['?', '?'], ['?', '?']], [['?', '?'], ['?', '?'], ['?', '?']]]


<b>Dictionaries</b>

In [28]:
#1
num = range(1,6)
letter = ['a','b','c','d','e']
dict = {key: value for key, value in zip(num, letter)}
print(dict)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}


In [29]:
#2
4 in dict

True

In [30]:
#2
7 in dict

False

In [32]:
#3
'a' in dict.values()

True

In [33]:
#3
'z' in dict.values()

False

In [34]:
#4
dict[6] = 'f'
print(dict)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f'}


In [35]:
#5
dict.pop(2)
print(dict)

{1: 'a', 3: 'c', 4: 'd', 5: 'e', 6: 'f'}


In [37]:
#6
dictNum = {'x':700, 'y':56874, 'z':900}
maxVal = max(dictNum.values())
minVal = min(dictNum.values())
print("Max: ", maxVal)
print("Min: ", minVal)

Max:  56874
Min:  700


<b> Numpy </b>

In [2]:
import numpy as np

In [6]:
#1
arr = np.array(range(20))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
#2
arr2 = np.array(range(30,40))
print(arr2)

[30 31 32 33 34 35 36 37 38 39]


In [9]:
#3
arr_zeros = np.zeros((6,6))
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
#4
arr_ones = np.ones((4,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#5
sampleArray = np.array([[11,22,33],[44,55,66],[77,88,99]])
arr5 = sampleArray[:,2]
print(arr5)

[33 66 99]


In [15]:
#6
inputarr = np.array(range(12,38))
reverse = inputarr[::-1]
print(reverse)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [20]:
#7
CwHwMat = np.array([list(range(1 + 4 * i, 1 + 4 * (i + 1))) 
                            for i in range(4)])
print(CwHwMat)
slice1 = CwHwMat[0:2,1:3]
print(slice1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[2 3]
 [6 7]]


In [21]:
#8
slice2 = CwHwMat[1:4,2:4]
print(slice2)

[[ 7  8]
 [11 12]
 [15 16]]


In [27]:
#9
X = CwHwMat[:4,:3]
print(X)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [29]:
#9
Y = CwHwMat[:,3]
print(Y)

[ 4  8 12 16]


In [ ]:
#10


<b> Pandas </b>

In [1]:
import pandas as pd

In [6]:
#1
data = {'a': [100,150], 'b':[200,250], 'c':[300,350], 'd': [400,350], 'e':[800,850]}
df1 = pd.Series(data)
print(df1)

a    [100, 150]
b    [200, 250]
c    [300, 350]
d    [400, 350]
e    [800, 850]
dtype: object


In [7]:
#2
data = [[2,3,4],[5,6,7]]
df2 = pd.Series(data)
print(df2)

0    [2, 3, 4]
1    [5, 6, 7]
dtype: object


In [4]:
#3
data = {'a': [100,150], 'b':[200,250], 'c':[300,350], 'd': [400,350], 'e':[800,850]}
df1 = pd.DataFrame(data)
print(df1)

     a    b    c    d    e
0  100  200  300  400  800
1  150  250  350  350  850


In [8]:
#4
data2 = pd.DataFrame([175, 275, 375, 475, 875])
df3 = pd.concat(df1, data2)


TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"

In [52]:
#5
df3.to_csv("CwHwA01242428")

In [9]:
#6
pokemon = pd.read_csv('pokemon.csv')
pokemon.head()

#        Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1   Bulbasaur  Grass  Poison    318  45      49       49       65       65   
1  2     Ivysaur  Grass  Poison    405  60      62       63       80       80   
2  3    Venusaur  Grass  Poison    525  80      82       83      100      100   
3  4  Charmander   Fire     NaN    309  39      52       43       60       50   
4  5  Charmeleon   Fire     NaN    405  58      64       58       80       65   

   Speed  Generation  Legendary  
0     45           1      False  
1     60           1      False  
2     80           1      False  
3     65           1      False  
4     80           1      False

In [10]:
#7
pokemon.tail()

#       Name   Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
146  147    Dratini   Dragon     NaN    300   41      64       45       50   
147  148  Dragonair   Dragon     NaN    420   61      84       65       70   
148  149  Dragonite   Dragon  Flying    600   91     134       95      100   
149  150     Mewtwo  Psychic     NaN    680  106     110       90      154   
150  151        Mew  Psychic     NaN    600  100     100      100      100   

     Sp. Def  Speed  Generation  Legendary  
146       50     50           1      False  
147       70     70           1      False  
148      100     80           1      False  
149       90    130           1       True  
150      100    100           1       True

In [55]:
#8
pokemon.

In [56]:
#9

In [57]:
#10

In [58]:
#11

In [59]:
#12

In [60]:
#13